# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d874a313cc2d848f6684e916cb099a16ae644877acd708b58ff857c6e4d9b5544ac2f85fe89ffbd1dc66ad221906b9074c90a79011f6922b6a578c530bffc9f

test:
  secret_key_base: 32d21992b705073b6d71749e1206ac7ef77efaa444349d0eedc9663a71ea2b851ca4de599a049d6c41a8b33207ac4a2e178ac575c36a3a65434e16dc0201ff8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
